# Waiting for other statements to complete.;
#;
# Creating table.;
create table rgd__mart.TEMP__0 as select a.description as description,a.entrez_gene_id as entrez_gene_id,a.name as name,a.rgd_id_key as rgd_id_key,a.symbol as symbol from rgd_temp__mart.rgd_genes__genetable__main as a;
# Merging two tables.;
create table rgd__mart.TEMP__2 as select a.rgd_id_key,b.uniprot_acc as uniprot_acc from rgd__mart.TEMP__0 as a left join rgd_temp__mart.rgd_genes__uniprot__dm as b on a.rgd_id_key=b.rgd_id_key;
# Merging two tables.;
create table rgd__mart.TEMP__6 as select a.rgd_id_key,b.DB_reference as DB_reference,b.PW_id as PW_id,b.PW_term as PW_term,b.aspect as aspect,b.evidence as evidence,b.qualifier as qualifier,b.with_from as with_from from rgd__mart.TEMP__0 as a left join rgd_temp__mart.rgd_genes__pwontology__dm as b on a.rgd_id_key=b.rgd_id_key;
# Merging two tables.;
create table rgd__mart.TEMP__16 as select a.rgd_id_key,b.accession as accession,b.accession_type as accession_type from rgd__mart.TEMP__0 as a left join rgd_temp__mart.rgd_genes__accessions__dm as b on a.rgd_id_key=b.rgd_id_key;
# Merging two tables.;
create table rgd__mart.TEMP__14 as select a.rgd_id_key,b.slim_id as slim_id,b.slim_term as slim_term from rgd__mart.TEMP__0 as a left join rgd_temp__mart.rgd_genes__geneontology_slim__dm as b on a.rgd_id_key=b.rgd_id_key;
# Merging two tables.;
create table rgd__mart.TEMP__10 as select a.rgd_id_key,b.DB_reference as DB_reference,b.MP_id as MP_id,b.MP_term as MP_term,b.aspect as aspect,b.evidence as evidence,b.qualifier as qualifier,b.with_from as with_from from rgd__mart.TEMP__0 as a left join rgd_temp__mart.rgd_genes__mpontology__dm as b on a.rgd_id_key=b.rgd_id_key;
# Merging two tables.;
create table rgd__mart.TEMP__4 as select a.rgd_id_key,b.chromosome as chromosome,b.mapped_repseq as mapped_repseq,b.score as score,b.start as start,b.stop as stop,b.strand as strand,b.version as version from rgd__mart.TEMP__0 as a left join rgd_temp__mart.rgd_genes__map31__dm as b on a.rgd_id_key=b.rgd_id_key;
# Merging two tables.;
create table rgd__mart.TEMP__18 as select a.rgd_id_key,b.DB_reference as DB_reference,b.DO_id as DO_id,b.DO_term as DO_term,b.aspect as aspect,b.evidence as evidence,b.qualifier as qualifier,b.with_from as with_from from rgd__mart.TEMP__0 as a left join rgd_temp__mart.rgd_genes__diseaseontology__dm as b on a.rgd_id_key=b.rgd_id_key;
# Merging two tables.;
create table rgd__mart.TEMP__12 as select a.rgd_id_key,b.chromosome as chromosome,b.mapped_repseq as mapped_repseq,b.score as score,b.start as start,b.stop as stop,b.strand as strand,b.version as version from rgd__mart.TEMP__0 as a left join rgd_temp__mart.rgd_genes__map34__dm as b on a.rgd_id_key=b.rgd_id_key;
# Merging two tables.;
create table rgd__mart.TEMP__8 as select a.rgd_id_key,b.DB_reference as DB_reference,b.GO_id as GO_id,b.GO_term as GO_term,b.aspect as aspect,b.evidence as evidence,b.qualifier as qualifier,b.with_from as with_from from rgd__mart.TEMP__0 as a left join rgd_temp__mart.rgd_genes__geneontology__dm as b on a.rgd_id_key=b.rgd_id_key;
# Waiting for other statements to complete.;
#;
# Waiting for other statements to complete.;
#;
# Creating index.;
create index TEMP__0_I_0 on rgd__mart.TEMP__0(rgd_id_key);
# Creating index.;
create index TEMP__8_I_1 on rgd__mart.TEMP__8(rgd_id_key);
# Creating index.;
create index TEMP__4_I_2 on rgd__mart.TEMP__4(rgd_id_key);
# Creating index.;
create index TEMP__12_I_3 on rgd__mart.TEMP__12(rgd_id_key);
# Creating index.;
create index TEMP__16_I_4 on rgd__mart.TEMP__16(rgd_id_key);
# Creating index.;
create index TEMP__6_I_5 on rgd__mart.TEMP__6(rgd_id_key);
# Creating index.;
create index TEMP__10_I_6 on rgd__mart.TEMP__10(rgd_id_key);
# Creating index.;
create index TEMP__14_I_7 on rgd__mart.TEMP__14(rgd_id_key);
# Creating index.;
create index TEMP__2_I_8 on rgd__mart.TEMP__2(rgd_id_key);
# Creating index.;
create index TEMP__18_I_9 on rgd__mart.TEMP__18(rgd_id_key);
# Waiting for other statements to complete.;
#;
# Renaming table.;
rename table rgd__mart.TEMP__16 to rgd__mart.rgd_genes__accessions__dm;
# Renaming table.;
rename table rgd__mart.TEMP__12 to rgd__mart.rgd_genes__map34__dm;
# Renaming table.;
rename table rgd__mart.TEMP__4 to rgd__mart.rgd_genes__map31__dm;
# Renaming table.;
rename table rgd__mart.TEMP__8 to rgd__mart.rgd_genes__geneontology__dm;
# Renaming table.;
rename table rgd__mart.TEMP__18 to rgd__mart.rgd_genes__diseaseontology__dm;
# Renaming table.;
rename table rgd__mart.TEMP__14 to rgd__mart.rgd_genes__geneontology_slim__dm;
# Renaming table.;
rename table rgd__mart.TEMP__10 to rgd__mart.rgd_genes__mpontology__dm;
# Renaming table.;
rename table rgd__mart.TEMP__2 to rgd__mart.rgd_genes__uniprot__dm;
# Renaming table.;
rename table rgd__mart.TEMP__0 to rgd__mart.rgd_genes__genetable__main;
# Renaming table.;
rename table rgd__mart.TEMP__6 to rgd__mart.rgd_genes__pwontology__dm;
# Waiting for other statements to complete.;
#;
